### ISSUE TITLE
[BUG] Difference in working of login command when running binary and docker image

### ISSUE THREAD

**Issue by Darkhood148** [goharbor/harbor-cli#418]
## Issue:
The `login` command works differently when using a locally built binary and when using Docker.
## Steps to reproduce:
+ Rename or delete the current config file:
```
mv ~/.config/harbor-cli/config.yaml ~/.config/harbor-cli/abcd
```
+ Run this command to build binary:
```
go build -o harbor-cli cmd/harbor/main.go
```

+ Run the login command on the newly built binary:
```
./harbor-cli login https://demo.goharbor.io -u harbor-cli -p Harbor12345
```
+ Check the config.yaml:
```
cat ~/.config/harbor-cli/config.yaml
```
You will get an output as:
```
credentials:
    - name: harbor-cli@demo-goharbor-io
      username: harbor-cli
      password: Harbor12345
      serveraddress: https://demo.goharbor.io
current-credential-name: harbor-cli@demo-goharbor-io
```

+ Now run:
```
harbor login https://demo.goharbor.io -u harbor-cli -p Harbor12345
```
+ Again check the `config.yaml` file:
```
cat ~/.config/harbor-cli/config.yaml
```

This time you will get something like:
```
credentials:
    - name: harbor-cli@demo-goharbor-io
      username: harbor-cli
      password: 4jUzzMVF5wxlhfCM3rWHXR9SNwN35fqE1dR4duCI6QObwAlEidyd
      serveraddress: https://demo.goharbor.io
current-credential-name: harbor-cli@demo-goharbor-io
```
Notice the modified password field. This causes authentication errors in other commands
